# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

  target 'SaryTask' do
    use_frameworks!
    pod ‘RxSwift’
    pod ‘RxCocoa’
    pod 'Kingfisher', '6.0'
  target 'SaryTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SaryTaskUITests' do
    # Pods for testing
  end

end
